# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'csdemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end
